# Generated by Django 5.2.8 on 2025-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_email_alter_users_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_attempts',
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='login_attem_email_370f9c_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='login_attem_ip_addr_bdf4e7_idx')],
            },
        ),
    ]
