# Generated by Django 5.2.8 on 2025-11-23 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_qty',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item_category',
            name='item_cat_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user'], name='item_user_id_bfcae1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name'], name='item_item_na_be79f0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['available_qty'], name='item_availab_a26b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_cat'], name='item_item_ca_fdc834_idx'),
        ),
        migrations.AddIndex(
            model_name='item_category',
            index=models.Index(fields=['user'], name='item_catego_user_id_1a8760_idx'),
        ),
        migrations.AddIndex(
            model_name='item_category',
            index=models.Index(fields=['item_cat_name'], name='item_catego_item_ca_c418bd_idx'),
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='item_category',
            table='item_category',
        ),
    ]
